name: Build

on:
  push:
    branches: [ main ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup-scala
        uses: olafurpg/setup-scala@v10
    
      - name: Run tests
        run: sbt test
